### ISSUE TITLE
Копирование репозиториев на другой аккаунт

### ISSUE THREAD

**Issue by ivan-varyukhin** [Medical-Information/medical-information-portal#105]

**Comment by GritsenkoSerge** [comment]
тут кажется все просто (делов на час-полтора)
- выставляем в существующих репах настройку "Template repository"
- создаем в новой организации репозитории на основе указанных выше шаблонов
- в корневом репозитория меняем ссылки на подмодули
- ручками добавляем необходимые для CI/CD переменные и секреты

**Comment by ivan-varyukhin** [comment]
проблема как минимум в том, что при создании репозитория из шаблона, мы теряем историю коммитов...
при форке она вроде сохраняется, но там скорее всего другие ограничения т.к. от не считается самостоятельным...
и в обеих случаях мы теряем список Contributors

**Comment by ivan-varyukhin** [comment]
Нашел такой вариант https://stackoverflow.com/questions/17371150/moving-git-repository-content-to-another-repository-preserving-history но у меня выдает ошибки авторизации (но на работе это нормально к сожалению)
